HOR-1654 "Error: when you open a case in Participated when is a Dummy Task" SOLVED
Issue:
    Error: when you open a case in Participated when is a Dummy Task
Cause:
    Caracter "-" es utilizado en la funcion "explode"
Solution:
    Se cambia el caracter "-" por "|"